// The event-driven monthly report, end to end:
//
//   portfolio saved / "Finished monthly update" clicked
//     -> evaluate the month's manual accounts (shared/monthlySync.js)
//     -> COMPLETE: make sure the month has a checkpoint, then schedule a
//        report job 10 minutes out (debounce: a correction inside the window
//        just pushes the job back; one after it produces a new version)
//     -> job: build the model -> HTML -> PDF (Puppeteer) -> storage
//        -> reports row -> in-app notification (+ optional email link)
//
// Everything external (storage, the PDF renderer, the e-mail sender, FX
// rates, the clock) is injected, so the whole flow runs in tests.
const crypto = require('crypto');
const { evaluateSyncStatus, syncFingerprint, nextSyncState, targetMonthFor, isValidMonth, monthEnd, previousMonth, nextMonth } = require('../../shared/monthlySync');
const { buildReportModel } = require('./reportModel');
const { renderReportHtml, monthLabel } = require('./reportHtml');
const { buildHoldingsIndex } = require('../holdingsIndex');

const DEBOUNCE_MS = 10 * 60 * 1000;
// The typed-in account categories a monthly sync is about.
const MANUAL_CATEGORIES = ['pension', 'cashFunds', 'bank'];
const JOB_NAME = 'report.render';

const num = (v) => {
  const n = Number(v);
  return Number.isFinite(n) ? n : 0;
};

// A monthly checkpoint built from the stored portfolio, for a month the
// user completed without saving one from the tracker page. Same shape as
// utils/monthlySnapshotBreakdown.js; values come from the prices stored
// with the portfolio.
function breakdownFromPortfolio(portfolio, asOf = new Date()) {
  const p = portfolio || {};
  const stockItems = (lots, market) => {
    const bySymbol = new Map();
    (lots || []).forEach((lot) => {
      const key = String(lot.stockName || '').trim();
      if (!key || !(num(lot.quantity) > 0)) return;
      const price = num(lot.currentPrice || lot.purchasePrice);
      const value = market === 'american' ? num(lot.quantity) * price * num(lot.currentExchangeRate || lot.exchangeRate) : num(lot.quantity) * price;
      const entry = bySymbol.get(key) || { key, label: lot.officialName ? `${lot.officialName} (${key})` : key, value: 0 };
      entry.value += value;
      bySymbol.set(key, entry);
    });
    return [...bySymbol.values()];
  };
  const years = (from) => Math.max(0, (asOf.getTime() - Date.parse(`${from}T00:00:00Z`)) / (365.25 * 86400000));
  return {
    israeli: stockItems(p.israeliStocks, 'israeli'),
    american: stockItems(p.americanStocks, 'american'),
    pension: (p.pensionFunds || []).map((f) => ({ key: f.fundName || `pension-${f.id}`, label: f.fundName || 'קופת גמל', value: num(f.currentValue != null ? f.currentValue : f.amount) })),
    cashFunds: (p.cashFunds || []).map((f) => ({ key: f.fundName || `cash-${f.id}`, label: f.fundName || 'קרן כספית', value: num(f.amount) })),
    bank: (p.bankBalances || []).map((b, i, all) => ({ key: `bank-${i + 1}`, label: all.length > 1 ? `עו"ש #${i + 1}` : 'עו"ש', value: num(b.amount) })),
    bankSavings: (p.bankSavingsFunds || []).map((f) => ({
      key: f.fundName || `bank-savings-${f.id}`,
      label: f.fundName || 'קופת חיסכון בבנק',
      value: (f.deposits || []).reduce((s, d) => s + num(d.amount) * Math.pow(1 + num(f.interestRate) / 100, years(d.date)), 0)
    })),
    autoGenerated: true
  };
}

const sumBreakdown = (b) =>
  ['israeli', 'american', 'pension', 'cashFunds', 'bank', 'bankSavings'].reduce(
    (s, k) => s + (Array.isArray(b[k]) ? b[k].reduce((t, i) => t + num(i.value), 0) : 0),
    0
  );

const hashModel = (model) => {
  const copy = Object.assign({}, model);
  delete copy.generatedAt;
  return crypto.createHash('sha256').update(JSON.stringify(copy)).digest('hex');
};

function createReportService({
  store,
  features,
  storage,
  renderer,
  notifier = { async reportReady() {} },
  getUsdRate = async () => null,
  debounceMs = DEBOUNCE_MS,
  now = () => new Date(),
  logger = console
}) {
  async function loadPortfolio(userId) {
    const raw = await store.getPortfolioPayload(userId);
    try {
      return raw ? JSON.parse(raw) : {};
    } catch {
      return {};
    }
  }

  async function currentStatus(userId, month) {
    return (await features.getSyncStatus(userId, month)) || { month, state: 'OPEN', excluded: [], fingerprint: null, version: 0 };
  }

  const jobKey = (userId, month, version) => `report:${userId}:${month}:v${version}`;

  // Schedules (or re-debounces) the report for the month's CURRENT content.
  // A job for this version still waiting -> push it back; otherwise (none
  // yet, or that version already rendered) -> a new version.
  async function scheduleReport(userId, month, status) {
    const runAfter = new Date(now().getTime() + debounceMs).toISOString();
    if (status.version > 0) {
      const existing = await features.findJobByKey(jobKey(userId, month, status.version));
      if (existing && existing.status === 'queued') {
        await features.rescheduleJob(existing.id, runAfter);
        return { version: status.version, jobId: existing.id, runAfter, debounced: true };
      }
    }
    const version = status.version + 1;
    const job = await features.enqueueJob(JOB_NAME, { userId, month, version }, { idempotencyKey: jobKey(userId, month, version), runAfter, maxAttempts: 3 });
    await features.saveSyncStatus(userId, month, Object.assign({}, status, { version }));
    return { version, jobId: job.id, runAfter, debounced: false };
  }

  // The report reads the month's saved checkpoint. The accounts this sync
  // is about (typed-in values) are brought into it from the portfolio, so
  // a correction made after completion reaches the next report version;
  // stock values stay as the user saved them. With no checkpoint for the
  // month at all, one is created from the portfolio's stored prices.
  async function syncSnapshot(userId, month, portfolio) {
    const snapshots = await store.listMonthlySnapshots(userId);
    const existing = snapshots.find((s) => s.month === month);
    const fresh = breakdownFromPortfolio(portfolio, now());
    if (!existing) {
      await store.upsertMonthlySnapshot(userId, month, sumBreakdown(fresh), JSON.stringify(fresh));
      return 'created';
    }
    const breakdown = Object.assign({}, existing.breakdown || {});
    if (breakdown.autoGenerated) {
      Object.assign(breakdown, fresh);
    } else {
      MANUAL_CATEGORIES.forEach((key) => {
        breakdown[key] = fresh[key];
      });
    }
    const total = sumBreakdown(breakdown);
    if (JSON.stringify(breakdown) === JSON.stringify(existing.breakdown) && Math.abs(total - num(existing.totalValueILS)) < 0.005) return 'unchanged';
    await store.updateMonthlySnapshot(userId, month, total, JSON.stringify(breakdown));
    return 'updated';
  }

  // Marks the month complete (by the user's button, or automatically once
  // every required account is updated) and schedules its report.
  async function completeMonth(userId, month, { by = 'user' } = {}) {
    if (!isValidMonth(month)) throw new Error('month must be YYYY-MM');
    const portfolio = await loadPortfolio(userId);
    const status = await currentStatus(userId, month);
    const evaluation = evaluateSyncStatus(portfolio, month, { excluded: status.excluded });
    const snapshot = await syncSnapshot(userId, month, portfolio);
    const next = Object.assign({}, status, {
      state: 'COMPLETE',
      fingerprint: syncFingerprint(evaluation),
      completedAt: status.completedAt || now().toISOString(),
      completedBy: status.completedBy || by
    });
    await features.saveSyncStatus(userId, month, next);
    const scheduled = await scheduleReport(userId, month, next);
    return { evaluation, snapshot, scheduled };
  }

  // Called after every portfolio save / ledger change. Advances the state
  // machine for the month being synced and, once complete, turns later
  // corrections into a new (debounced) report version.
  async function onPortfolioSaved(userId) {
    const month = targetMonthFor(now().toISOString().slice(0, 10));
    const portfolio = await loadPortfolio(userId);
    const status = await currentStatus(userId, month);
    const evaluation = evaluateSyncStatus(portfolio, month, { excluded: status.excluded });
    const state = nextSyncState(status.state, evaluation);

    if (status.state !== 'COMPLETE' && state === 'COMPLETE') {
      return { month, action: 'completed', result: await completeMonth(userId, month, { by: 'auto' }) };
    }
    if (status.state === 'COMPLETE') {
      const fingerprint = syncFingerprint(evaluation);
      if (fingerprint !== status.fingerprint) {
        await syncSnapshot(userId, month, portfolio);
        const next = Object.assign({}, status, { fingerprint });
        await features.saveSyncStatus(userId, month, next);
        return { month, action: 'rescheduled', result: await scheduleReport(userId, month, next) };
      }
      return { month, action: 'none' };
    }
    if (state !== status.state || !(await features.getSyncStatus(userId, month))) {
      await features.saveSyncStatus(userId, month, Object.assign({}, status, { state }));
    }
    return { month, action: 'state', state };
  }

  async function getStatus(userId, month) {
    const portfolio = await loadPortfolio(userId);
    const status = await currentStatus(userId, month);
    const evaluation = evaluateSyncStatus(portfolio, month, { excluded: status.excluded });
    const reports = (await features.listReports(userId)).filter((r) => r.month === month);
    const pendingJob = status.version > 0 ? await features.findJobByKey(jobKey(userId, month, status.version)) : null;
    return {
      month,
      state: status.state === 'COMPLETE' ? 'COMPLETE' : nextSyncState(status.state, evaluation),
      version: status.version,
      completedAt: status.completedAt || null,
      completedBy: status.completedBy || null,
      accounts: evaluation.accounts,
      updatedCount: evaluation.updatedCount,
      requiredCount: evaluation.required.length,
      pendingReport: pendingJob && (pendingJob.status === 'queued' || pendingJob.status === 'running') ? { version: status.version, runAfter: pendingJob.runAfter, status: pendingJob.status } : null,
      reports
    };
  }

  async function setExcluded(userId, month, keys) {
    const status = await currentStatus(userId, month);
    await features.saveSyncStatus(userId, month, Object.assign({}, status, { excluded: [...new Set(keys.map(String))] }));
    return getStatus(userId, month);
  }

  async function userEmail(userId) {
    const row = await store.sql.get('SELECT email FROM users WHERE id = ?', [userId]);
    return row ? row.email : '';
  }

  // The job handler.
  async function renderReport({ userId, month, version }) {
    const existing = await features.getReportByVersion(userId, month, version);
    if (existing && existing.status === 'ready') return { reportId: existing.id, skipped: 'already rendered' };
    await features.upsertReport({ userId, month, version, status: 'rendering' });
    try {
      const [snapshots, portfolio, transactions, status, targets, email] = await Promise.all([
        store.listMonthlySnapshots(userId),
        loadPortfolio(userId),
        store.listTransactions(userId),
        currentStatus(userId, month),
        store.getRebalanceTargets(userId),
        userEmail(userId)
      ]);
      const evaluation = evaluateSyncStatus(portfolio, month, { excluded: status.excluded });
      const { byUser } = buildHoldingsIndex([{ userId, portfolio }]);
      const info = byUser.get(userId);
      const next = nextMonth(month);
      const events = info
        ? await features.listMarketEvents(info.positions.map((p) => ({ symbol: p.symbol, market: p.market })), `${next}-01`, monthEnd(next))
        : [];
      const [usdRateEnd, usdRatePrev] = await Promise.all([
        getUsdRate(monthEnd(month)).catch(() => null),
        getUsdRate(monthEnd(previousMonth(month))).catch(() => null)
      ]);
      const model = buildReportModel({
        userEmail: email,
        month,
        snapshots,
        portfolio,
        transactions,
        events,
        syncStatus: evaluation,
        targets,
        usdRateEnd,
        usdRatePrev,
        generatedAt: now().toISOString()
      });
      const dataHash = hashModel(model);

      // Identical content to the latest ready version -> reuse its file.
      const previousReady = (await features.listReports(userId)).find((r) => r.month === month && r.status === 'ready' && r.version !== version);
      let storageKey;
      let bytes;
      let reused = false;
      if (previousReady && previousReady.dataHash === dataHash) {
        storageKey = previousReady.storageKey;
        bytes = previousReady.bytes;
        reused = true;
      } else {
        const pdf = await renderer.render(renderReportHtml(model));
        storageKey = `reports/${userId}/${month}/v${version}.pdf`;
        await storage.put(storageKey, pdf);
        bytes = pdf.length;
      }
      const report = await features.upsertReport({ userId, month, version, status: 'ready', storageKey, bytes, dataHash, reused });

      await features.insertAlert({
        userId,
        type: 'REPORT_READY',
        severity: 'info',
        sessionDate: month,
        instrument: null,
        title: `הדוח החודשי ל${monthLabel(month)} מוכן`,
        message: `גרסה ${version} של הדוח החודשי מוכנה להורדה בעמוד "דוחות".`,
        recommendation: { action: 'NO_ACTION', text: 'אפשר להוריד את הדוח מעמוד הדוחות.' },
        dedupKey: `report:${userId}:${month}:v${version}`,
        createdAt: now().toISOString()
      });
      try {
        const prefs = (await features.getPreferences(userId, 'reports')) || {};
        if (prefs.emailOnReady && email) {
          const link = storage.signedUrl ? await storage.signedUrl(storageKey, 7 * 24 * 3600) : null;
          await notifier.reportReady({ to: email, month, monthLabel: monthLabel(month), version, link });
        }
      } catch (err) {
        logger.error('[reports] email failed', err && err.message);
      }
      return { reportId: report.id, version, reused, bytes };
    } catch (err) {
      await features.upsertReport({ userId, month, version, status: 'failed', error: String(err && err.message) });
      throw err;
    }
  }

  async function downloadTarget(userId, reportId) {
    const report = await features.getReport(userId, reportId);
    if (!report || report.status !== 'ready' || !report.storageKey) return null;
    return { report, target: await storage.downloadTarget(report.storageKey, 60) };
  }

  // A fresh version on demand (e.g. after fixing a snapshot).
  async function regenerate(userId, month) {
    const status = await currentStatus(userId, month);
    if (status.state !== 'COMPLETE') throw new Error('the month is not complete yet');
    return scheduleReport(userId, month, status);
  }

  return { onPortfolioSaved, completeMonth, getStatus, setExcluded, renderReport, downloadTarget, regenerate, scheduleReport };
}

// Optional e-mail on report ready via Resend (https://resend.com), when
// RESEND_API_KEY and REPORT_EMAIL_FROM are set. The PDF is never attached -
// the mail carries a link (a 7-day signed URL when Supabase Storage is in
// use, otherwise the app's reports page).
function createEmailNotifier(env = process.env, { post } = {}) {
  const apiKey = env.RESEND_API_KEY;
  const from = env.REPORT_EMAIL_FROM;
  if (!apiKey || !from) return { enabled: false, async reportReady() {} };
  const send = post || ((url, body, config) => require('axios').post(url, body, config));
  const appUrl = (env.APP_URL || '').replace(/\/+$/, '');
  return {
    enabled: true,
    async reportReady({ to, monthLabel: label, version, link }) {
      const href = link || (appUrl ? `${appUrl}/reports` : null);
      const html = `<div dir="rtl" style="font-family:Arial,sans-serif">
        <p>הדוח החודשי של StockView ל${label} (גרסה ${version}) מוכן.</p>
        ${href ? `<p><a href="${href}">להורדת הדוח</a>${link ? ' (הקישור בתוקף 7 ימים)' : ''}</p>` : '<p>אפשר להוריד אותו מעמוד הדוחות באפליקציה.</p>'}
      </div>`;
      await send('https://api.resend.com/emails', { from, to, subject: `StockView - דוח חודשי ${label}`, html }, { headers: { Authorization: `Bearer ${apiKey}` }, timeout: 15000 });
    }
  };
}

module.exports = { createReportService, createEmailNotifier, breakdownFromPortfolio, hashModel, JOB_NAME, DEBOUNCE_MS };
